apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  labels:
    app: mbeng44/vote
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mbeng44/vote
  template:
    metadata:
      labels:
        app: mbeng44/vote
    spec:
      containers:
      - name: vote
        image: mbeng44/vote:latest
        ports:
        - containerPort: 80
